### ISSUE TITLE
ADSR not responding v2.6

### ISSUE THREAD

**Issue by stanislavche** [twistedelectrons/TherapSID#108]
When I play throw midi (M8 -> Therapsid 1st Midi channel) ADSR setting not responding on the fly. I need to restart playback to hear this changes.
I have received Therapsid yesterday it has 2.6 firmware from 1st of February. On Therapsid tool v1.2 I have set ADSR Bug: to fixed for both Sid. But it’s not helped. I have installed Swinsids in 6581 mode.
Any ideas or solutions, may be this already been discussed?

**Comment by thomasj** [comment]
Hi!

This is normal for the SID, as you will need to restart playback to hear the changes of the envelope. The changes are written to the SID directly when changed.

Note that the Therapsid Tool (and TS) only supports special functionality/settings of the ARMSID chips. If there are special commands to Swinsid to disable ADSR bug, they are most likely not the same.
However, the ADSR bug is not related to the issue you see. 

Thereby, suggesting @twisted-electrons to close this issue as Invalid.

**Comment by stanislavche** [comment]
For those who play it from trackers or daw. If you want to hear changes on the fly don’t forget to send midi note off. In other case ADSR won’t respond till you stop playback.

**Comment by thomasj** [comment]
Yes, NoteOn with velocity 0 is handled as NoteOff.
