### ISSUE TITLE
SID volume control

### ISSUE THREAD

**Issue by Windfisch** [twistedelectrons/TherapSID#17]
**Describe the solution you'd like**
Control the volume register using shift + poti (e.g. filter mode + filter cutoff)

**Describe alternatives you've considered**
Not control it: Could leave out some interesting ways to deal with distortion (?)
Control it using buttons only: tedious

**Comment by twisted-electrons** [comment]
filter button + scrub knob controls volume, but the webmidi tool also allows us to change it
