### ISSUE TITLE
sustain pedal up doesn't kill sustained voices

### ISSUE THREAD

**Issue by twisted-electrons** [twistedelectrons/TherapSID#21]
sustain pedal up doesn't kill sustained voices

**Comment by Windfisch** [comment]
I investigated this a little. The following works fine for me, no bug present:

1. Send "pedal down" CC on channel 1.
2. Play some notes on channel 1. _Notes "hang" as expected._
3. Send "pedal up" CC on channel 1. _Notes now release as expected._

However, the bug manifests when using the channels 2-4:
1. Send "pedal down" on channel 1.
2. Play notes on channels 2, 3 or 4. _Notes hang, kinda unexpectedly_
3. Send "pedal up" on channel 1. _Notes continue to hang. Bug!_
4. Play some notes on channels 2-4. _The voice reacts but always falls back to the hanging note_.
5. Play the hanging note on channels 2-4 and release. _The Note-off finally kills the note._

**Comment by Sequence7** [comment]
That seems like it is caught up in the multitimbral issue I posted.

**Comment by twisted-electrons** [comment]
unrelated to multitimbral issue but fixed
