### ISSUE TITLE
Glide not functional on channel 2, 3 and 4

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#24]
**Describe the bug**
Glide knobs do nothing when legato notes are sent on their corresponding channels 2, 3, 4

**Steps To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Turn up glide knob
2. Play two notes in legato i.e hold one note then hold another on midi keyboard / sequencer

**Actual behavior**
Second note plays but glide does not function.

**Expected behavior**
Should glide to frequency of next note.

**Additional context**
Being that channel 2 , 3, and 4 are most likely going to be Sequenced the glide function should be compatible with how monophonic sequencers handle slides, (different to how it works on the main channel) , if therapsid receives a note on, on say note 61 then another note on, on 72, that's followed immediately by a note off from 61, it should continue its glide. The way the main channel does it, is nice for playing on a keyboard, but it isn't compatible with slide functions on sequencers.

**Comment by Sequence7** [comment]
Hi @Windfisch any update on this. Seems like the last main bug/missing function

**Comment by Windfisch** [comment]
Hey @Sequence7, sorry I haven't had the time to look into it until now. Gonna have a look today.

**Comment by Windfisch** [comment]
Hey @Sequence7, I've (hopefully) implemented a fix: The new behavior is as follows:

- Glide is only enabled in monophonic mode. In Paraphonic / polyphonic modes, glide is always off.
- When a voice is not overridden using channels 2,3,4: It glides when the master channel is played "legato", i.e. when the old note is still held while the new is already played.
- When a voice is overridden using channels 2,3,4: It glides when the overriding channel is played "legato"

You can try out the fix [here](https://github.com/twistedelectrons/TherapSID/blob/artifacts/pr81-firmware.syx?raw=true)

**Be aware** that I implemented this blindly (I don't have the hardware to test around right now). There is a small chance that this renders the firmware completely unusable (no reaction to keypresses or notes, no sound). In this case, just flash the old one again for now.

**Comment by Sequence7** [comment]
Hi @Windfisch pretty close for a blind build thanks. Only issue I've noticed is channels 2, 3, 4 does not require legato so it always glides to the knob value.

**Comment by Windfisch** [comment]
@Sequence7 try again with [the new version](https://github.com/twistedelectrons/TherapSID/blob/artifacts/pr81-firmware.syx?raw=true). Apparently, channel-2,3,4-notes got registered twice which made the TherapSID always think they're legato. Should be fixed now.

**Comment by Sequence7** [comment]
@Windfisch I'd like to test it a little further with sequencing, but initially it seems to be all working correctly now, thank you

**Comment by twisted-electrons** [comment]
@Windfisch Thanks for doing this! I haven't obseved any performance issues with the extra load on the ISR. I have one doubt: Is a glide communly expected when falling from second note back to the first? I don't have many synths with legato but my sub37 glides from second finger back to first... TherapSid doesn't do this (same for master note)...

**Comment by Sequence7** [comment]
I think you are right @twisted-electrons , I polled some friends to check their gear also and this is how most synths work.

**Comment by twisted-electrons** [comment]
@Sequence7 Thanks for polling and confirming, it felt that way. I'll check with @Windfisch the best way to proceed. Thanks!

**Comment by thomasj** [comment]
Yes, this is called "mono note priority" and there are some different variants. The most common is "last note priority" which does what you wish, but some (often older) synths have "low note" or "high note" priority. Some synths have it as a setting. I'm all for the last note priority - most playable!

**Comment by Windfisch** [comment]
I haven't modified the gliding mechanics compared to the old TherapSID firmware, i.e. the "glide on legato" and "mono note priority" things were there already before.

With the current firmware, you can glide back to the first note by retriggering the first note.

i.e.:
hold C, hold G -> glide upwards
holding G, release C and press again -> glide downwards

I personally think that mono note prio can lead to glitchy sounds (trills) when playing quickly, which kinda suits the TherapSID's overall character, but your call, Alex :D

29.05.2023 10:21:33 Twisted Electrons ***@***.***>:

**Comment by twisted-electrons** [comment]
@Windfisch Thanks for the clarification. @thomasj  thanks for your input too :) I've continued to play with it as-is and enjoy the option to glide or jump as currently implemented, I like how we can alternate between glidey and jumpy trills as needed. I vote to keep it like this but I'd be happy to add an option to the tool at a later date
