### ISSUE TITLE
Program change always goes to preset 01

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#25]
**Describe the bug**
Send a program change to change presets and it always goes to preset 01 regardless of program number sent

**Steps To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Send program change from a sequencer with a value between 2 and 99

**Actual behavior**
Therapsid sets preset to 01,regardless of value

**Expected behavior**
Expected behavior is if I send a program change with value of 50, Therapsid will change to preset 50 

**Additional context**
Have tried various bank values as well, sent same program change to my yamaha and roland sound modules and they change to expected preset.

**Comment by Windfisch** [comment]
Hi, thank you for reporting this!

Can you check whether https://github.com/twistedelectrons/TherapSID/pull/28 fixes this for you? You can find the compiled firmware in the "Pull request artifacts" [comment](https://github.com/twistedelectrons/TherapSID/pull/28#issuecomment-1474886363).

**Comment by Sequence7** [comment]
Thank you, I tested and it was working correctly now :) Out of the bugs left the multitimbral one is most halting me from doing the project for twisted electrons with tuning coming in after that. Appreciate your work!

**Comment by Windfisch** [comment]
Closing via #28
