### ISSUE TITLE
CC#20 and CC#34 are not functional

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#26]
**Describe the bug**
When sending CC values, to CC#20 Voice 3 fine tune, LCD does not update value nor does the voice 3 pitch change.
When sending CC#34 values with arp set to off, while sending chord notes, manually sweeping scrub knob works, sweeping cc range does not. 

**Steps To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Send CC messages to 20 while listening to voice 3 and watching lcd.
2. Sweep CC#34 range while holding a chord, does not scrub

**Actual behavior**
CC#20 gets no response from Therapsid
CC#34 gets no response from Therapsid

**Expected behavior**
CC#20 should adjust voice 3 fine tune, like it's voice2 and voice1 counterparts behave, lcd should reflect value change.
CC#34 should be the same as adjusting value of the scrub knob

**Additional context**
Perhaps when moving the scrub knob or CC the LCD should reflect what step scrub is on (unless this interferes with speed), I think every other CC I tried showed values on LCD (and I tried them all)

**Comment by twisted-electrons** [comment]
CC#20 was indeed a bug (fixed) But Scrub is confirmed working. Was the held chord and sent CC on MIDI master channel? Will investigate display update
