### ISSUE TITLE
Tuning is off at default settings

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#27]
**Describe the bug**
with fine set to 0 and Tune set to 0, an A is 451hz

**Steps To Reproduce**
Steps to reproduce the behavior, e.g.:
play an A midi note on a single triangle

**Actual behavior**
It is 451hz, requires considerable detuning of fine knob to play nice with other instruments

**Expected behavior**
I expected it to be closer to 440hz, I know it may not be exact but my commodore 64 on same note is 439hz

**Additional context**
The tuning lists for sid chips when in a commodore 64 are different depending whether it is PAL or NTSC (50hz vs 60hz)
I am not sure if Therapsid is using one of these lists at the wrong hz or was done custom. Either way, this needs a look at.

**Comment by Sequence7** [comment]
Hi Florian, Sounds Fair, If you are saying only some notes are out of tune then I can't imagine anyone who made previous patches or music specifically wanted some notes out of tune. A toggle is fine though if anyone felt strongly about it.

**Comment by Windfisch** [comment]
No, the whole instrument is consistent in itself, because all notes are equally off. In essence, the whole device is tuned some 50ish cents off.

let's ask @twisted-electrons about the tuning backwards compatibility issue.

**Comment by Sequence7** [comment]
Perhaps then holding a button and moving a tune knob could be a master tune (it would need to save this when turned off) , having a master tune on a digital synth is a bit weird though. I think as musical instrument it should default to being in tune. I appreciate the notion of backwards compatibility but not when it's preventing using the device for its intended purpose.

**Comment by Windfisch** [comment]
Default to "properly tuned" with an option to detune it in a way that restores the original tuning sounds reasonable to me.

**Comment by Sequence7** [comment]
After talking with @twisted-electrons in email about this there was a suggestion that full left on the fine knob could be 440hz. I initially said this wouldn't work because modulation needs to go above and below. But I have now tested the lfo frequencies and they are Unipolar (only go above frequency fine knob is set to) so this should be ok. Perhaps an option bipolar lfo's could be the Web app they would be not have their range limited by knob being bottomed out.

**Comment by twisted-electrons** [comment]
After further thoughts and discussion I think it's best that the C440 is located at the center (noon) position of the fine knobs as in previous implmentations. I will add an option for bipolar LFO but I still feel it is important to manually detune voices up AND down with the knob.
I hacked the note to frequency lookup table to increase the overall frequency by a quarter tone. This seems to bring the presets back to their original pitch without breaking the new pitch engine. (update to be pushed today)
