### ISSUE TITLE
LFO's need to not be RETRIG by voices that are not mapped to that LFO (fix second)

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#32]
**Describe the bug**
This is probably just something that was not previously tested or implemented in a way that supports multitimbral voices.
if voice 1 is not mapped to any LFO's it should not cause LFO's to retrigger

**Expected behavior**
Voices should only cause an LFO retrigger if that LFO is mapped to that voice. 

**Additional context**
Examples, 
if voice 1 has lfo1 mapped PWM with retrig on, and I send a note to voice 2 it should not retrig voice' 1's lfo. 

if I have 3 LFO's mapped to voice 3, then voice 1 and 2 have no lfo's mapped they should not retrigger any LFO's but voice 3 should retrigger all LFO's

If LFO1 is mapped to voice 1 and voice 3, then sending a note to voice 1 OR voice 3 should retrigger LFO1, but sending a note to voice 2 should not retrigger LFO1.

I hope that makes sense enough, this is necessary because if you have for an easy example an lfo modulating a PWM pad on voice 2 and have a fast lead melody on voice 1 it should not be resetting the pwm on voice 2. every time voice 1 plays

**Comment by twisted-electrons** [comment]
This should be fixed... I sent you a syx to try :)

**Comment by Sequence7** [comment]
Not found any issues with this fix. Closing this now
