### ISSUE TITLE
Preset: Can't store (or load?) a fat mode value >4

### ISSUE THREAD

**Issue by twisted-electrons** [twistedelectrons/TherapSID#33]
**Describe the bug**
Can't save a fat mode value >4
Is it intentional? We appear to be writing 3 bytes so 0-7 range should be possible?

**Steps To Reproduce**
Steps to reproduce the behavior, e.g.:
1. change fate mode to 5
2. save preset
3. load preset > fat mode is 2

**Expected behavior**
Expecting to be able to save any fat modes

**Comment by Windfisch** [comment]
Definitely not intentional. Maybe we are not *reading* the 3 bits back? Or maybe we are, but then there's some clamping happening. Hmmm

**Comment by thomasj** [comment]
This one was fixed with recently merged #45 so can now be closed.

**Comment by twisted-electrons** [comment]
Thansk thomasj, nice one!
