### ISSUE TITLE
Saving Preset 99 will destroy Global settings and vice versa

### ISSUE THREAD

**Issue by thomasj** [twistedelectrons/TherapSID#44]
**Describe the bug**
The EEPROM memory locations for Global settings (adress 3986 to 3999) clashes with the locations of Preset 99 (3960 to 3999). This means that saving Preset 99 will destroy Global settings, and vice versa - changing Global settings will affect Preset 99. 

**Steps To Reproduce**
1. Holding down ARP and press DOWN to enter editing of Master MIDI Out channel 
2. Using UP/DOWN, select "03".
3. Save by pressing ARP again. 
4. Set RESONANCE to another value, say "07".
5. Save the Preset on number 99
6. Restart the unit
7. Holding down ARP and press DOWN to enter editing of Master MIDI Out channel again

**Actual behavior**
The Master MIDI OUT channels shows "07" (i.e same as the Resonance above)

**Expected behavior**
The Master MIDI OUT channels should show "03" (i.e as set by the user).

**Additional context**
This was found after having submitted PR #43 which fixed corrupted Global settings, and I wanted to understand _why_ it was corrupted. According to [preset.cpp](https://github.com/twistedelectrons/TherapSID/blob/6d26e8299c79035a2b6f6abb7b2f718ad7ec144f/src/preset.cpp#L12-L13) the 99 positions for presets should reside in the location 0-3960, leaving room for the global settings up to 3999. However, due to how the location is calculated, we never use memory positions 0-39, instead actually using 40 to 3999 for presets 1 to 99. https://github.com/twistedelectrons/TherapSID/blob/6d26e8299c79035a2b6f6abb7b2f718ad7ec144f/src/preset.cpp#L263

***Suggestion for improvements***
* If not already used by the boot loader or other, use range 0-39 for global settings instead (leaving all Presets intact).
* Make some other nice improvements:
  * Use `#define`s for fixed EEPROM locations  
  * Add a cookie header (first two bytes for instance) to validate that memory has been formatted
  * Add two bytes to determine EEPROM structure version. This means we can convert one format to another, if needed in the future
  * There is still free space between 4000 and 4095 for further data. If we reserve three of the bytes in the 0-39 space we have one more byte for extra preset data storage. Could be handy when doing new features.

**Comment by twisted-electrons** [comment]
Hi Thomasj, welcome and thanks for joining the party! I look forward to checking this out when back in the office Thurday!

**Comment by twisted-electrons** [comment]
Hi ThomasJ !
Totally agree with your suggestions (nice find!). 
I'll create defines for the settings and move them to location 0, can do this as soon as Friday.
An extra byte per preset will be handy indeed. We could use 2 nibbles (and a third should be available in the current preset space) to store the duty cycle of the 3 LFO lfos (4bit should be enough to have fun). Unless we want to use it for something more important...

**Comment by thomasj** [comment]
Did some work on it and made a pull request, which also includes some refactoring to minimise duplicated code and flash footprint.

**Comment by twisted-electrons** [comment]
Amazing! Can't wait to check it out - Thanks!

**Comment by thomasj** [comment]
Closing this one, since #49 is now merged.

**Comment by thomasj** [comment]
Worth noting maybe, is that upon first using this firmware with the globals moved, they will be reset to default values.
