### ISSUE TITLE
Enable filter per voice

### ISSUE THREAD

**Issue by thomasj** [twistedelectrons/TherapSID#51]
**Background**
The SID chip is capable of routing any combination of voices to the filter. Many times, and specifically when used in multitimbral mode, it can be quite useful to utilise this feature. One example could be having the bass on voice 1 routed through the low pass filter whereas the main lead and effects on voice 2 and 3 goes unfiltered, for instance.

**Enhancement suggestion**
Holding down the Filter button and then clicking on a voice's currently enabled Waveform button would disable the filter routing for that voice. It could be indicated by flashing (or turning off) the LED. 
Normal presses of the Filter button would work just as today, changing the filter type and at the same time enabling it for all voices again (thereby having identical functionality for users that doesn't use this "power" feature).

**Comment by twisted-electrons** [comment]
Hi Thomasj thanks for the suggestion, sorry if I missunderstood but I believe that's acuatlly how it is currently implemented. Hold filter mode and click a waveform to connect/disconnect the voice to the filter...

**Comment by Sequence7** [comment]
Yes I use this feature a lot with the 6581 (don't think it's documented in manual though)

**Comment by thomasj** [comment]
Ah, wrote the ticket without having my unit in front to me :) Didn't see it being mentioned and also saw it wasn't stored in the preset. Anyway, good that it is there and I saw that with a commit yesterday it is now also stored! I might have some ideas on optimising this for having space for more things going forward - will submit a PR for you to check later on, @twisted-electrons! Let's close this ticket!
