### ISSUE TITLE
A more reliable way to save presets.

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#58]
**issue**
Not sure if it's just me but when saving a preset it often just goes up or down one preset when I press both buttons and then thinks I want to save one of those instead and I've just lost what I was working on. Or it does start flashing and I press both the buttons and it quickly goes up or down and saves over the wrong preset and I lose what I had previously finished working on. 
I Seem to have about 30% success rate to saving a preset and not losing anything  

I don't know if the window of the timing needs to be increased or another solution but I just can't reliably make this work.

**Comment by twisted-electrons** [comment]
Agreed! On the MEGA fm we have a timer that autosaves after a few seconds (with increased flash rate). Feels nicer...

**Comment by twisted-electrons** [comment]
HI Thomas thanks for the feedback, I reverted and will try improving the original version as advised...

**Comment by twisted-electrons** [comment]
I don't believe it was possible to cancel save mode in the past but it's a great idea to use reset.

**Comment by twisted-electrons** [comment]
I submitted a new pull request: Tweaked scroll speed (starts slower), and preset up/down debouncing to avoid accidental preset changes during or after a save. Also changed duty cycle of blink so we see the number longer.
I was had 10/10 sucess rate saving to new locations and we now have about 1 second window to press both buttons...

**Comment by Sequence7** [comment]
This seems to be working great now, thank you.  Closing this one.
