### ISSUE TITLE
Arp to change frequency inside envelope

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#62]
**Describe the solution you'd like**
Adding this so Thomas can see everything being worked on. Have discussed with Twisted electrons about a toggle for this. 

Currently the envelopes run within in the Arp. When you release the arp it rings put on whatever note it was up to. 
In chiptune an arp will change frequency within the envelope and you continue to hear the arp in the release stage. Both ways have many uses but this is how it traditionally is on the c64 and chiptune in general.

**Comment by twisted-electrons** [comment]
I see the use for this but unsure of the best way to implment it

**Comment by Sequence7** [comment]
I have thought about. And yes. There's multiple difficulties now I really thought about how it work. It could only work on 1 voice since they have their own envelopes. Unless they ran independently each with in their own envelopes. It would have to just rotate through frequencies and rate set by the arp. The real problem is it needs to remember these frequencies so when it sends gate off's to the sid those frequencies continue to rotate while the user is no longer touching midi keyboard. After release finishes these would still be rotating in the background and on a real sid chip you would hear it distantly through the oscillator bleed. I think if @thomasj implements the wavetable this might become redundant. I'd like to hear your thoughts about it Thomas
