### ISSUE TITLE
ARMSID configuration support

### ISSUE THREAD

**Issue by thomasj** [twistedelectrons/TherapSID#67]
### Background
TherapSID supports ARMSID chips, currently with a yes/no setting in the web app to tweak some timings. The ARMSID is quite advanced and supports several different profiles regarding filter and SID emulation (6581/8580) type. These settings can currently be set by using a real C64 and running a configuration program. Many TherapSID users have no access to a C64 but could still benefit from accessing these settings when seated in the unit. It could also be good to have it as a plug-and-play ready system (just inserting one or two ARMSID chips and let the detection be automatic). 

### Describe the solution you'd like
* Remove the ARMSID yes/no setting in the configuration web app
* Support for 3 SIDs, both in ASID and regular synth mode
* With 3 SIDs - 9-voice polyphony over MIDI
* Improve ARMSID timing
* Add the following settings to the web app (separate for the two sockets):
  - Chip type (6581/8580)
  - 6581 Filter Strength
  - 6581 Lowest Filter Frequency
  - 8580 Filter Central Frequency
  - 8580 Lowest Filter Frequency
  - ADSR bug fix on/off
* When changing settings, they would be immediately saved to TS EEPROM, and then used by the ARMSID
* Flashing settings to actual ARMSID should also be possible by holding down a button during power-on

### Note
_Description above was a bit different from the beginning, but evolved during development into the above_

**Comment by Sequence7** [comment]
I know at least 1 person who would be very happy to hear this, there is also a pi shield that can do it. I put the armsids in my real c64 one by one, and use the config to turn off adsr bug and adjust the filter. Even with a real c64 it is a bit of a process. I have two single armsids, but I know others use the one that's connected by the cable between them, the arm2sid.

**Comment by oemsysadm** [comment]
This would be amazing. Do you have an ARM2SID? That particular product can emulate a third SID chip, addressed separately, with sound output from both "normal" SID sound outputs. 9 voice polyphony on the TherapSID? :D

**Comment by thomasj** [comment]
An ARM2SID is incoming :) Don't know the feasibility of 9-voice polyphony but would be interesting to try!

**Comment by thomasj** [comment]
Received the ARM2SID and started hacking, fun! Have been able to configure the chip (emulation and filter properties) from the TS, so have created configuration entrypoints for future Web app extensions. It was also, with some special cabling etc, possible to utilize the third on-chip SID. Haven't tried out 9-voice polyphonic playing yet, but have it so far running within the ASID playback/remix framework. Here an in-development demo of playing a 3SID C64 file:

https://www.instagram.com/reel/CupM3jrsuvl

**Comment by ledeniz** [comment]
Happy to find this issue, as I have 2 ARMSIDs that waited to be inserted into my TherapSID that arrived today and I would love to be able to configure them properly.

Regarding the proposed changes for the webapp: is that one in this repo (or open source) too? I was looking for the source to find out what the "ARMSID mode" checkbox actually does.

**Comment by thomasj** [comment]
The web app changes are not in this repo (at least not yet), but that app is mainly just sending MIDI commands in order to set/unset the options. 
The current function of the "ARMSID mode" option sets the "armsid" mode for the chips, which affects the timing of signals. However, during my ARMSID implementation activities I took a look at it and could see that neither of the modes have the correct timings :) So when this #67 is done, there will be no timing differences between SID and ARMSID. Might even remove the box entirely then.

**Comment by thomasj** [comment]
> * In the firmware - add automatic ARMSID detection (for one or two chips).
Btw, this autodetection feature can not be done since the TherapSID has (hardware wise) no way to read back info from the SID chips. So it would either be a checkbox (like today) - or better : none at all, since the commands to the ARMSID would anyway not affect a regular SID.

**Comment by thomasj** [comment]
The ARMSID support is now implemented in a few ways (pull request not yet created, but upcoming in some days) :
 * Timing fixes, no longer requiring a separate SID/ARMSID setting
 * Configuration of the emulation of 2 slots, using the Twisted Electrons web tool
 * Support for 3 SIDs, both in ASID and regular synth mode
 * With 3 SIDs - 9-voice polyphony over MIDI
 * Enhanced/bug fixed detuning (no longer uneven over octaves)
 * Enhanced ASID using Turbo MIDI, where up to 3 SIDs and also the FM chip can be utilized (requires updated DeepSID player, submitted elsewhere)
 
Small demo here:
https://youtu.be/Stwx9ZNehRc

**Comment by thomasj** [comment]
Closing ticket, as the pull request #89 was released in TherapSID firmware version 2.5

**Comment by xeno6696** [comment]
Apologies for resurrecting a closed issue, but it isn't clear to me how to achieve the arm2sid flashing.  The manual does provide a reference to THIS link:

https://twisted-electrons.com/tool/TherapSID/arm2sid.zip

But there's no zip file at that location and it just points to the online web-based tool select page.  I am interested in getting to 9 voices.
